/* Lumen UI kit — sample content. Exposed as window.LUMEN_DATA. */
window.LUMEN_DATA = {
  tracks: [
    { n: '01', title: 'Foundations', lessons: 5, mins: 40, desc: 'What AI actually is, how it works, and the words you need to talk about it with confidence.', tone: 'pine' },
    { n: '02', title: 'In the Classroom', lessons: 7, mins: 55, desc: 'Practical, classroom-ready ways to use AI for planning, resources and feedback.', tone: 'clay' },
    { n: '03', title: 'Ethics & Discernment', lessons: 6, mins: 50, desc: 'A Catholic lens on dignity, discernment and the right use of technology.', tone: 'ochre' },
    { n: '04', title: 'Safety & Privacy', lessons: 4, mins: 30, desc: 'Student data, safeguarding and the CEWA policies that keep everyone protected.', tone: 'pine' },
    { n: '05', title: 'Assessment & Integrity', lessons: 5, mins: 45, desc: 'Rethinking assessment and academic integrity in a world with AI.', tone: 'clay' },
  ],

  tools: [
    { id: 'magicschool', name: 'MagicSchool AI', vendor: 'magicschool.ai', status: 'approved', featured: true, popular: true,
      subject: 'All subjects', category: 'Planning',
      desc: 'Generate lesson plans, rubrics and differentiated resources in minutes.',
      long: 'MagicSchool brings 70+ teaching tools into one place — lesson and unit planning, rubric generation, text levelling, IEP support and more. Built for educators, with a student-safe "MagicStudent" mode and clear data controls.',
      roles: ['Classroom teacher', 'Curriculum lead'],
      tags: ['Lesson planning', 'Differentiation', 'Rubrics', 'IEP support'],
      notes: ['Student-data handling reviewed and approved for CEWA schools.', 'MagicStudent mode is age-gated and teacher-controlled.', 'Free for individual teachers; school plans available.'] },

    { id: 'brisk', name: 'Brisk Teaching', vendor: 'briskteaching.com', status: 'pilot', popular: true,
      subject: 'All subjects', category: 'Feedback',
      desc: 'A Chrome extension that gives feedback, levels texts and builds quizzes right where you work.',
      long: 'Brisk layers onto Google Docs, Slides and the web, so you can give targeted feedback, adjust reading levels and generate quizzes without leaving your workflow. Approved for a guided classroom pilot.',
      roles: ['Classroom teacher'],
      tags: ['Feedback', 'Reading levels', 'Quizzes', 'Google Workspace'],
      notes: ['Approved for guided pilots — confirm with your AI lead first.', 'Runs as a browser extension; review permissions on install.'] },

    { id: 'diffit', name: 'Diffit', vendor: 'diffit.me', status: 'approved', featured: true,
      subject: 'English', category: 'Differentiation',
      desc: 'Turn any topic, text or video into ready-to-use, level-adapted resources.',
      long: 'Diffit takes a topic, article or YouTube link and produces a reading passage at the level you choose, plus vocabulary, questions and activities — a fast on-ramp to differentiation.',
      roles: ['Classroom teacher', 'Support teacher'],
      tags: ['Differentiation', 'Reading', 'Comprehension'],
      notes: ['Approved for use across CEWA schools.', 'Always review generated passages for accuracy and tone.'] },

    { id: 'curipod', name: 'Curipod', vendor: 'curipod.com', status: 'approved',
      subject: 'All subjects', category: 'Engagement',
      desc: 'Build interactive lessons with polls, word clouds and open responses in one click.',
      long: 'Curipod generates interactive, discussion-rich lessons from a prompt, with live polls, drawings and open-ended responses to keep students thinking.',
      roles: ['Classroom teacher'],
      tags: ['Interactive lessons', 'Engagement', 'Formative'],
      notes: ['Approved for classroom use.', 'Student responses can be anonymous.'] },

    { id: 'khanmigo', name: 'Khanmigo', vendor: 'khanacademy.org', status: 'review',
      subject: 'Mathematics', category: 'Tutoring',
      desc: 'An AI tutor and teaching assistant grounded in Khan Academy content.',
      long: 'Khanmigo acts as a Socratic tutor for students and a planning aide for teachers, anchored to Khan Academy\u2019s curriculum. Currently under CEWA review for student-facing use.',
      roles: ['Classroom teacher', 'Student-facing'],
      tags: ['Tutoring', 'Maths', 'Socratic'],
      notes: ['Under review — not yet cleared for student-facing use in CEWA schools.', 'Teacher-facing planning features can be explored.'] },

    { id: 'twee', name: 'Twee', vendor: 'twee.com', status: 'approved',
      subject: 'English', category: 'Planning',
      desc: 'AI tools made for English teachers — texts, questions, dialogues and more.',
      long: 'Twee specialises in English language teaching: generate reading and listening texts, comprehension questions, dialogues, and discussion prompts pitched to a chosen level.',
      roles: ['Classroom teacher'],
      tags: ['English', 'Reading', 'Speaking'],
      notes: ['Approved for use.', 'Best paired with your own texts for context.'] },

    { id: 'canva', name: 'Canva Magic Studio', vendor: 'canva.com', status: 'approved', popular: true,
      subject: 'The Arts', category: 'Design',
      desc: 'Design classroom visuals, worksheets and slides with AI assistance.',
      long: 'Magic Studio adds AI design, writing and image tools to Canva for Education, which CEWA schools already license. Strong guardrails are in place for school accounts.',
      roles: ['Classroom teacher', 'Leadership'],
      tags: ['Design', 'Worksheets', 'Slides', 'Visuals'],
      notes: ['Approved via the existing Canva for Education agreement.', 'AI image features are restricted on student accounts.'] },

    { id: 'eduaide', name: 'Eduaide.ai', vendor: 'eduaide.ai', status: 'pilot',
      subject: 'All subjects', category: 'Planning',
      desc: 'A planning assistant with 150+ resource types and a feedback bot.',
      long: 'Eduaide helps you draft a wide range of teaching resources and refine them in a workspace, with a feedback assistant for student work. Approved for a guided pilot.',
      roles: ['Classroom teacher', 'Curriculum lead'],
      tags: ['Lesson planning', 'Resources', 'Feedback'],
      notes: ['Pilot only — coordinate with your AI lead.'] },

    { id: 'quizizz', name: 'Quizizz AI', vendor: 'quizizz.com', status: 'approved',
      subject: 'All subjects', category: 'Assessment',
      desc: 'Generate quizzes and lessons, then run them live or as homework.',
      long: 'Quizizz AI drafts quizzes and lessons from your content or a topic, with accommodations and reports. Widely used and approved for CEWA classrooms.',
      roles: ['Classroom teacher'],
      tags: ['Quizzes', 'Formative', 'Homework'],
      notes: ['Approved for use.', 'Review AI-generated questions before assigning.'] },

    { id: 'notebooklm', name: 'NotebookLM', vendor: 'google.com', status: 'pilot',
      subject: 'HASS', category: 'Research',
      desc: 'Ground an AI assistant in your own documents for summaries and study guides.',
      long: 'NotebookLM keeps the AI anchored to sources you upload, producing summaries, study guides and audio overviews with citations — useful for staff research and senior students.',
      roles: ['Classroom teacher', 'Leadership'],
      tags: ['Research', 'Summarising', 'Citations'],
      notes: ['Pilot for staff and senior, supervised use.', 'Check document sensitivity before uploading.'] },

    { id: 'gamma', name: 'Gamma', vendor: 'gamma.app', status: 'review',
      subject: 'All subjects', category: 'Design',
      desc: 'Turn a prompt or outline into polished slide decks and docs.',
      long: 'Gamma generates presentations, documents and webpages from a short prompt. Under review for data-handling before classroom rollout.',
      roles: ['Classroom teacher', 'Leadership'],
      tags: ['Slides', 'Presentations'],
      notes: ['Under review — staff exploration only for now.'] },

    { id: 'character', name: 'Character.AI', vendor: 'character.ai', status: 'restricted',
      subject: 'All subjects', category: 'Chatbot',
      desc: 'Open-ended chatbot personas — not suitable for student-facing use.',
      long: 'Character.AI lets users chat with open-ended AI personas. Content moderation is insufficient for a school setting; it is not approved for student-facing use in CEWA schools.',
      roles: ['Staff awareness'],
      tags: ['Chatbot'],
      notes: ['Not approved for student-facing use.', 'Listed so staff can recognise and advise families.'] },
  ],

  statusFilters: [
    { key: 'approved', label: 'CEWA Approved' },
    { key: 'pilot', label: 'Pilot' },
    { key: 'review', label: 'Under review' },
    { key: 'restricted', label: 'Not approved' },
  ],
  subjects: ['All subjects', 'English', 'Mathematics', 'HASS', 'The Arts'],
  categories: ['Planning', 'Differentiation', 'Feedback', 'Assessment', 'Engagement', 'Design', 'Research', 'Tutoring'],
};
